name: air_quality
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  core_libs:
    path: ../../packages/core_libs

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/PM25Icon.jpeg
    - assets/images/PM10Icon.png
    - assets/images/OzoneIcon.png
    - assets/images/UVIcon.png
    - assets/images/town_main.png

 