name: core
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  core_libs:
    path: ../../packages/core_libs
  air_quality:
    path: ../air_quality
  map:
    path: ../map
  cupertino_icons: ^1.0.6
  go_router: ^14.1.1
  google_nav_bar: ^5.0.6
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
